{
    'name' : 'Parking Management System',
    'version' : '10.1.0.0',
    'author' : 'Jakc Labs',
    'category' : 'Generic Modules/Parking Management System',
    'depends' : ['base','hr', 'product', 'account', 'sale'],
    'init_xml' : [],
    'data' : [
        'security/jakc_parking_security.xml',
        'security/ir.model.access.csv',
        'views/jakc_parking_view.xml',
        'views/jakc_parking_booth_view.xml',
        'views/jakc_parking_pricing_view.xml',
        'views/jakc_parking_transaction_view.xml',
        'views/res_partner_view.xml',
        'views/product_view.xml',
        'views/jakc_parking_sequence.xml',
        'views/jakc_parking_menu.xml',
        'views/templates.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}