{
    'name' : 'Parking Management System',
    'version' : '1.0',
    'author' : 'Jakc Labs',
    'category' : 'Generic Modules/Parking Management System',
    'depends' : ['base_setup','base','hr', 'product', 'account', 'sale'],
    'init_xml' : [],
    'data' : [            
        'security/jakc_parking_security.xml',
        'security/ir.model.access.csv',
        'wizard/jakc_parking_membership_payment_invoice_view.xml',
        'wizard/jakc_parking_transaction_session_correction_view.xml',                         
        'jakc_parking_view.xml',
        'jakc_parking_booth_view.xml',
        'jakc_parking_customer_view.xml',        
        'jakc_parking_pricing_view.xml',
        'jakc_parking_transaction_view.xml',     
        'jakc_parking_operator_view.xml',        
        'jakc_parking_sequence.xml',        
        'jakc_parking_menu.xml',
        #'jakc_parking_config_view.xml',
        #'jakc_parking_config_menu.xml',       
         
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}